language: python
python:
  - "2.7"
# cache: pip

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest --flakes --cov=greengo tests/ # or py.test for Python versions 3.5 and below
